version: '{build}'
clone_depth: 1
environment:
  matrix:
    - VIM_URL: http://vim-jp.org/redirects/koron/vim-kaoriya/vim74/oldest/win64/
    - VIM_URL: http://vim-jp.org/redirects/koron/vim-kaoriya/vim80/oldest/win64/
    - VIM_URL: http://vim-jp.org/redirects/koron/vim-kaoriya/latest/win64/
install:
- ps: |
    $zip = $Env:APPVEYOR_BUILD_FOLDER + '\vim.zip'
    $vim = $Env:APPVEYOR_BUILD_FOLDER + '\vim\'

    $redirect = Invoke-WebRequest -URI $Env:VIM_URL
    (New-Object Net.WebClient).DownloadFile($redirect.Links[0].href, $zip)

    [Reflection.Assembly]::LoadWithPartialName('System.IO.Compression.FileSystem') > $null
    [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $vim)

    $Env:THEMIS_VIM = $vim + (Get-ChildItem $vim).Name + '\vim.exe'
build: off
test_script:
- ps: |
    & $Env:THEMIS_VIM --version
    .\bin\themis.bat --reporter dot
deploy: off
