environment:
  matrix:
    - RUBY_VERSION: 25
    - RUBY_VERSION: 24
    - RUBY_VERSION: 23
    - RUBY_VERSION: 22

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;C:\tools\neovim\Neovim\bin;%PATH%
  - set NVIM_RUBY_LOG_LEVEL=DEBUG
  - set NVIM_RUBY_LOG_FILE=%cd%\ci.log
  - choco install neovim --pre -fy --ignore-dependencies
  - bundle install

build: off

branches:
  only:
    - master

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - nvim -v

test_script:
  - bundle exec rake
